site_name: MkLorum

nav:
    - Home: index.md
    - cgroups: cgroups.md
    - Linux System Calls: linux-system-calls.md
    - Kubernetes: kubernetes.md
    - AWS: aws-land.md
    - HashiCorp Vault: vault.md
    - Elasticsearch: elasticsearch.md
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: true
